version: "3"
services:
  metube:
    build: 
      context: . 
      dockerfile: Dockerfile
    #image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8086:8081"
    volumes:
      volumes:
        - metube_data:/downloads
